In [5]:
# 1. Imports
import pandas as pd

In [6]:
# 2. Load CSVSs
# Load features and labels
features = pd.read_csv("features.csv")
labels = pd.read_csv("TrainLabels.csv")

print("Features shape:", features.shape)
print("Labels shape:", labels.shape)

# Preview
display(features.head())
display(labels.head())

Features shape: (3633, 737)
Labels shape: (5358, 5)

,filename,relative_path,1_AU01,1_AU02,1_AU04,1_AU05,1_AU06,1_AU07,1_AU09,1_AU10,...,3_rh_17_z,3_rh_18_x,3_rh_18_y,3_rh_18_z,3_rh_19_x,3_rh_19_y,3_rh_19_z,3_rh_20_x,3_rh_20_y,3_rh_20_z
0,1100011002.avi,110001\1100011002\1100011002.avi,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1100011003.avi,110001\1100011003\1100011003.avi,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1100011004.avi,110001\1100011004\1100011004.avi,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1100011005.avi,110001\1100011005\1100011005.avi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1100011006.avi,110001\1100011006\1100011006.avi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

           ClipID  Boredom  Engagement  Confusion  Frustration
0  1100011002.avi        0           2          0             0
1  1100011003.avi        0           2          0             0
2  1100011004.avi        0           3          0             0
3  1100011005.avi        0           3          0             0
4  1100011006.avi        0           3          0             0

In [7]:
# 3. Merge
# Merge on filename = ClipID
merged = pd.merge(
    features,
    labels,
    left_on="filename",
    right_on="ClipID",
    how="inner"   # only keep matches
)

print("Merged shape:", merged.shape)
display(merged.head())

Merged shape: (3618, 742)

,filename,relative_path,1_AU01,1_AU02,1_AU04,1_AU05,1_AU06,1_AU07,1_AU09,1_AU10,...,3_rh_19_y,3_rh_19_z,3_rh_20_x,3_rh_20_y,3_rh_20_z,ClipID,Boredom,Engagement,Confusion,Frustration
0,1100011002.avi,110001\1100011002\1100011002.avi,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1100011002.avi,0,2,0,0
1,1100011003.avi,110001\1100011003\1100011003.avi,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1100011003.avi,0,2,0,0
2,1100011004.avi,110001\1100011004\1100011004.avi,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1100011004.avi,0,3,0,0
3,1100011005.avi,110001\1100011005\1100011005.avi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1100011005.avi,0,3,0,0
4,1100011006.avi,110001\1100011006\1100011006.avi,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,1100011006.avi,0,3,0,0

In [ ]:
# 4. Reorder Columns
# Use only columns that actually exist
label_cols = [col for col in ["Boredom", "Engagement", "Confusion", "Frustration"] if col in merged.columns]

new_col_order = (
    list(merged.columns[:2]) + 
    label_cols + 
    [col for col in merged.columns[2:] if col not in label_cols and col != "ClipID"]
)

merged = merged[new_col_order]
display(merged.head())

,filename,relative_path,Boredom,Engagement,Confusion,1_AU01,1_AU02,1_AU04,1_AU05,1_AU06,...,3_rh_18_x,3_rh_18_y,3_rh_18_z,3_rh_19_x,3_rh_19_y,3_rh_19_z,3_rh_20_x,3_rh_20_y,3_rh_20_z,Frustration
0,1100011002.avi,110001\1100011002\1100011002.avi,0,2,0,1.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1,1100011003.avi,110001\1100011003\1100011003.avi,0,2,0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2,1100011004.avi,110001\1100011004\1100011004.avi,0,3,0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,1100011005.avi,110001\1100011005\1100011005.avi,0,3,0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
4,1100011006.avi,110001\1100011006\1100011006.avi,0,3,0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

In [9]:
# 4. Save Merged CSV
merged.to_csv("merged_features_labels.csv", index=False)
print("✅ Saved merged_features_labels.csv with", len(merged), "rows")

✅ Saved merged_features_labels.csv with 3618 rows